### ISSUE TITLE
How can I get gantt chart?

### ISSUE THREAD

**Issue by rlacjfjin** [mbenahmed1/ScheduleMe#10]
Hi,
I'm very curious for getting the gantt chart in your readme.md file.
Can you help me?
Thanks.

**Comment by mbenahmed1** [comment]
Hi,
you can generate these Gantt charts with the script `etc/plotter.py` using `matplotlib`. The docstring of `plotter.py` contains a description of the needed data format. 

```
n r
[cap]^r
id start proc [demand]^r
...
...

with 
    n:=         number of activities
    r:=         number of resources
    cap:=       capacity per resource

and each line after the second representing an activity with

    id:=        the id
    start:=     starting time
    proc:=      processing time
    demand:=    the demand of resource r of activity id

Example:

3 2
5 10
1 1 3 1 0
2 0 2 0 3
3 3 3 0 2
```

You can generate a `.plot` file in the needed format by passing the `--plot` flag to the scheduler.

**Comment by rlacjfjin** [comment]
Thank you very much!
It's a nice plot.
